version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo "Deploy Beginning"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          if [ "$BRANCH_NAME" = "master" ]; then
            echo "Syncing files with AWS w/ Cache Control Headers"
            aws s3 sync build/ "s3://${BUCKET_NAME}" --exclude "*.html" --delete --cache-control max-age=31557600
            aws s3 sync build/ "s3://${BUCKET_NAME}" --include "*.html" --cache-control max-age=0
          elif [ "$BRANCH_NAME" = "develop" ]; then
            echo "Syncing files with AWS"
            aws s3 sync build/ "s3://${BUCKET_NAME}" --delete
          fi
        else
          echo "Build/Deploy failure"
        fi
      - echo "Deploy Complete"
  post_build:
    commands:
      - echo "CodeBuild Status (0 == fail, 1 == success) - $CODEBUILD_BUILD_SUCCEEDING"
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          if [ "$BRANCH_NAME" = "master" ]; then
            echo Cloudfront ID - $CF_DIST_ID
            aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths /*
          fi
          echo "Build/Deploy success on branch ${BRANCH_NAME} on $(date)"
        else
          echo "Build/Deploy failure"
        fi
