// { value: value: 'Studio', label: value: 'STUDIO', name: 'residence' },
const states = [
  { value: 'AK', label: 'AK', name: 'state' },
  { value: 'AL', label: 'AL', name: 'state' },
  { value: 'AR', label: 'AR', name: 'state' },
  { value: 'AS', label: 'AS', name: 'state' },
  { value: 'AZ', label: 'AZ', name: 'state' },
  { value: 'CA', label: 'CA', name: 'state' },
  { value: 'CO', label: 'CO', name: 'state' },
  { value: 'CT', label: 'CT', name: 'state' },
  { value: 'DC', label: 'DC', name: 'state' },
  { value: 'DE', label: 'DE', name: 'state' },
  { value: 'FL', label: 'FL', name: 'state' },
  { value: 'GA', label: 'GA', name: 'state' },
  { value: 'GU', label: 'GU', name: 'state' },
  { value: 'HI', label: 'HI', name: 'state' },
  { value: 'IA', label: 'IA', name: 'state' },
  { value: 'ID', label: 'ID', name: 'state' },
  { value: 'IL', label: 'IL', name: 'state' },
  { value: 'IN', label: 'IN', name: 'state' },
  { value: 'KS', label: 'KS', name: 'state' },
  { value: 'KY', label: 'KY', name: 'state' },
  { value: 'LA', label: 'LA', name: 'state' },
  { value: 'MA', label: 'MA', name: 'state' },
  { value: 'MD', label: 'MD', name: 'state' },
  { value: 'ME', label: 'ME', name: 'state' },
  { value: 'MI', label: 'MI', name: 'state' },
  { value: 'MN', label: 'MN', name: 'state' },
  { value: 'MO', label: 'MO', name: 'state' },
  { value: 'MP', label: 'MP', name: 'state' },
  { value: 'MS', label: 'MS', name: 'state' },
  { value: 'MT', label: 'MT', name: 'state' },
  { value: 'NC', label: 'NC', name: 'state' },
  { value: 'ND', label: 'ND', name: 'state' },
  { value: 'NE', label: 'NE', name: 'state' },
  { value: 'NH', label: 'NH', name: 'state' },
  { value: 'NJ', label: 'NJ', name: 'state' },
  { value: 'NM', label: 'NM', name: 'state' },
  { value: 'NV', label: 'NV', name: 'state' },
  { value: 'NY', label: 'NY', name: 'state' },
  { value: 'OH', label: 'OH', name: 'state' },
  { value: 'OK', label: 'OK', name: 'state' },
  { value: 'OR', label: 'OR', name: 'state' },
  { value: 'PA', label: 'PA', name: 'state' },
  { value: 'PR', label: 'PR', name: 'state' },
  { value: 'RI', label: 'RI', name: 'state' },
  { value: 'SC', label: 'SC', name: 'state' },
  { value: 'SD', label: 'SD', name: 'state' },
  { value: 'TN', label: 'TN', name: 'state' },
  { value: 'TX', label: 'TX', name: 'state' },
  { value: 'UM', label: 'UM', name: 'state' },
  { value: 'UT', label: 'UT', name: 'state' },
  { value: 'VA', label: 'VA', name: 'state' },
  { value: 'VI', label: 'VI', name: 'state' },
  { value: 'VT', label: 'VT', name: 'state' },
  { value: 'WA', label: 'WA', name: 'state' },
  { value: 'WI', label: 'WI', name: 'state' },
  { value: 'WV', label: 'WV', name: 'state' },
  { value: 'WY', label: 'WY' }
];

export { states };
